name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: sudo apt install -y valgrind lcov
    - name: Build project
      run: scripts/build.sh
    - name: Upload code coverage reports
      run: bash <(curl -s https://codecov.io/bash)
