name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prerequisites
      run: sudo apt install -y lcov
    - name: build
      run: ./build.sh
