name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y valgrind lcov
      - run: scripts/build.sh
      - run: bash <(curl -s https://codecov.io/bash)
